USE [master]
GO

/****** Object:  Database [wop]    Script Date: 04/24/2012 08:38:08 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'wop')
DROP DATABASE [wop]
GO

USE [master]
GO

/****** Object:  Database [wop]    Script Date: 04/24/2012 08:38:09 ******/
CREATE DATABASE [wop] ON  PRIMARY 
( NAME = N'WOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.DBI\MSSQL\DATA\WOP.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.DBI\MSSQL\DATA\WOP_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [wop] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [wop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [wop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [wop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [wop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [wop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [wop] SET ARITHABORT OFF 
GO

ALTER DATABASE [wop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [wop] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [wop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [wop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [wop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [wop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [wop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [wop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [wop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [wop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [wop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [wop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [wop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [wop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [wop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [wop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [wop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [wop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [wop] SET  READ_WRITE 
GO

ALTER DATABASE [wop] SET RECOVERY FULL 
GO

ALTER DATABASE [wop] SET  MULTI_USER 
GO

ALTER DATABASE [wop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [wop] SET DB_CHAINING OFF 
GO


